"""Renders a `ProjectReport` as a Markdown document."""

from __future__ import annotations

from ai_workspace_assistant.models import ProjectReport


def human_size(num: int) -> str:
    """Format a byte count into a short human-readable string (e.g. ``1.5 KB``)."""
    value = float(num)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if abs(value) < 1024.0:
            if unit == "B":
                return f"{int(value)} B"
            return f"{value:.1f} {unit}"
        value /= 1024.0
    return f"{value:.1f} PB"


class MarkdownReporter:
    """Produces a Markdown summary of a scanned project."""

    format = "markdown"

    def render(self, report: ProjectReport) -> str:
        scan = report.scan
        extensions = report.get_extensions()
        languages = report.get_languages()

        lines: list[str] = []
        lines.append(f"# Project Report: {scan.root.name}")
        lines.append("")
        lines.append(
            f"_Generated by AI Workspace Assistant on "
            f"{report.generated_at.strftime('%Y-%m-%d %H:%M:%S')} (UTC)_"
        )
        lines.append("")

        lines.append("## Overview")
        lines.append("")
        lines.append(f"- **Project root:** `{scan.root}`")
        lines.append(f"- **Total files:** {scan.total_files}")
        lines.append(f"- **Total size:** {human_size(scan.total_size)}")
        lines.append(f"- **Directories scanned:** {scan.scanned_dirs}")
        lines.append(f"- **Languages detected:** {len(languages)}")
        lines.append("")

        lines.append("## Languages")
        lines.append("")
        if languages:
            lines.append("| Language | Files | Size |")
            lines.append("| --- | ---: | ---: |")
            for stat in languages:
                lines.append(f"| {stat.language} | {stat.files} | {human_size(stat.total_size)} |")
        else:
            lines.append("_No recognized languages found._")
        lines.append("")

        lines.append("## Files by Extension")
        lines.append("")
        if extensions:
            lines.append("| Extension | Count | Size |")
            lines.append("| --- | ---: | ---: |")
            for stat in extensions:
                label = stat.extension or "_(none)_"
                lines.append(f"| {label} | {stat.count} | {human_size(stat.total_size)} |")
        else:
            lines.append("_No files found._")
        lines.append("")

        if scan.warnings:
            lines.append("## Warnings")
            lines.append("")
            for warning in scan.warnings:
                lines.append(f"- {warning}")
            lines.append("")

        lines.append("---")
        lines.append("")
        return "\n".join(lines)
